SchoolAdmin/SchoolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from school_app.views import *
from school_app.facade import *
from school_app.api import *
from django.contrib.auth.decorators import   *
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    #BASE
    path('', IndexPageView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/login/', SchoolLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('obtain_auth_token/', obtain_auth_token, name='obtain_auth_token'),
    path('home/', TemplateView.as_view(template_name="bases/base.html"), name="home"),
    #API
    path('api_login/', api_login, name='api_login'),
    path('api_crear_estudiante/', SchoolCrearEstudiante.as_view(), name='api_crear_estudiante'),
    path('api_crear_editar_estudiantes/', SchoolCrearEditarEstudiante.as_view(), name='api_crear_editar_estudiantes'),
    path('api_consultar_estudiantes/', SchoolConsultarEstudiante.as_view(), name='api_consultar_estudiantes'),
    path('api_eliminar_estudiantes/', SchoolEliminarEstudiante.as_view(), name='api_eliminar_estudiantes'),
    path('api_datos_estudiantes/', SchoolConsultarDatosEstudiante.as_view(), name='api_datos_estudiantes'),
    #PAGES
    path('consultar_cursos/', ConsultarCursosView.as_view(), name='consultar_cursos'),
    path('consultar_estudiantes/', ConsultarEstudiantesView.as_view(), name='consultar_estudiantes'),
    path('estudiante_curso/<int:estudiante_id>/', EstudianteCursoView.as_view(), name='estudiante_curso'),
    #AJAX
    path('ajax/add_curso/', add_curso_ajax, name='add_curso_ajax'),
    path('ajax/get_info_curso/', get_info_curso, name='get_info_curso'),
    path('ajax/delete_curso_ajax/', delete_curso, name='delete_curso_ajax'),

    path('ajax/get_direcciones', get_direcciones, name='get_direcciones'),
    path('ajax/get_data_direccion', get_data_direccion, name='get_data_direccion'),
    path('ajax/create_edit_direccion', create_edit_direccion, name='create_edit_direccion'),
    path('ajax/delete_direccion', delete_direccion, name='delete_direccion'),

    path('ajax/add_estudiante_curso_ajax', add_estudiante_curso_ajax, name='add_estudiante_curso_ajax'),
    path('ajax/get_info_estudiante_curso', get_info_estudiante_curso, name='get_info_estudiante_curso'),
    path('ajax/delete_estudiante_curso', delete_estudiante_curso, name='delete_estudiante_curso'),
]

SchoolAdmin/school_app/models.py
from django.db import models

# Create your models here.

class Curso(models.Model):
    CodigoCurso = models.CharField(max_length=250)
    NombreCurso = models.CharField(max_length=250)
    FechaInicio = models.DateTimeField()
    FechaFin =  models.DateTimeField()
    FechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
    FechaActualizacion = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.CodigoCurso) +" - "+ self.NombreCurso

class Estudiante(models.Model):
    GENERO = [
        (0,"Femenino"),
        (1,"Masculino"),
        (2,"NoDefinido"),
        ]
    Nombres = models.CharField(max_length=300)
    Apellidos = models.CharField(max_length=300)
    FechaNacimento = models.DateTimeField()
    Genero =  models.IntegerField(choices=GENERO)
    FechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
    FechaActualizacion = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.Nombres +" "+ self.Apellidos

class Direccion(models.Model):
    TIPOS_DIRECCION = [
        (0,"Domicilio"),
        (1,"Laboral"),
        (2,"Temporal"),
        ]
    Direccion = models.CharField(max_length=500)
    Estudiante = models.ForeignKey(Estudiante, default = 1, on_delete=models.PROTECT)
    TipoDireccion =  models.IntegerField(choices=TIPOS_DIRECCION)
    FechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
    FechaActualizacion = models.DateTimeField(auto_now=True)

class Entidad(models.Model):
    EstaBorrado = models.BooleanField()
    FechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
    FechaBorrado = models.DateTimeField()
    FechaActualizacion = models.DateTimeField(auto_now=True)

class EstudianteCurso(models.Model):
    Estudiante = models.ForeignKey(Estudiante, default = 1, on_delete=models.PROTECT)
    Curso = models.ForeignKey(Curso, default = 1, on_delete=models.PROTECT)
    FechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
    FechaActualizacion = models.DateTimeField(auto_now=True)

class DoWork(models.Model):
    EstaBorrado = models.BooleanField(default=True)
    Evento = models.CharField(max_length=500)
    Fecha = models.DateTimeField(auto_now_add=True, auto_now=False)

SchoolAdmin/school_app/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm,authenticate
from django import forms
from .models import *
from django.contrib.auth.models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from crispy_forms.bootstrap import (
    Accordion, AccordionGroup, Alert, AppendedText, FieldWithButtons,
    InlineCheckboxes, InlineRadios, PrependedAppendedText, PrependedText,
    StrictButton, Tab, TabHolder,
)
# FORMULARIOS GENERADOS CORRESPONDIENTES A LOS MODELOS
class LoginForm(AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username=username,password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)
        return super(LoginForm, self).clean()

class CrearEditarCursoForm(forms.Form):
    codigo_curso = forms.CharField()
    nombre_curso = forms.CharField()
    fecha_inicio = forms.DateField(
            widget = forms.TextInput(
                attrs={'type': 'date'}
            )
        )
    fecha_fin = forms.DateField(
            widget = forms.TextInput(
                attrs={'type': 'date'}
            )
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column(Field('codigo_curso', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('nombre_curso', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('fecha_inicio', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('fecha_fin', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
            )
        )



class CrearEditarEstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        exclude = ('FechaCreacion','FechaActualizacion')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["FechaNacimento"] = forms.DateField(
            widget = forms.TextInput(
                attrs={'type': 'date'}
            )
        )
        self.helper = FormHelper()
        self.helper.layout = Layout(
             Row(
                Column(Field('Nombres', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('Apellidos', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('FechaNacimento', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('Genero', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
            ),
        )


class CrearEditarDireccionForm(forms.ModelForm):
    class Meta:
        model = Direccion
        exclude = ('FechaCreacion','FechaActualizacion','Estudiante')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
             Row(
                Column(Field('Direccion', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
                Column(Field('TipoDireccion', css_class="form-control form-control-sm"), css_class='form-group col-md-6 '),
            ),
        )

class CrearEditarEstudianteCursoForm(forms.ModelForm):
    class Meta:
        model = EstudianteCurso
        exclude = ('FechaCreacion','FechaActualizacion','Estudiante')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
             Row(
                Column(Field('Curso', css_class="form-control form-control-sm"), css_class='form-group col-md-12 '),
            ),
        )

SchoolAdmin/templates/pages/consultar_cursos.html
{% extends 'bases/base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load crispy_forms_tags %}
{% load humanize %}
<div id="shadowdiv" class="card">
    <div class="card-header"><h3>Consultar Cursos</h3></div>
    <div class="card-body">
        <div class="text-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" 
                data-target="#demoModal">Agregar Curso</button>
        </div>
        <div class="modal fade" id="demoModal" tabindex="-1" role="dialog" aria-labelledby="demoModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="demoModalLabel">Agregar Curso</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <form class="forms-sample" method="POST">{% csrf_token %}
                            {% crispy filter_form %}
                            <input type="number" style="display:none" id="id_curso_edit">
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="add_curso()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <table id="data_table" class="table table-striped">
            <thead>
                <tr>
                    <th>Codigo Curso</th>
                    <th>Nombre Curso</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr>
                        <td> <label> {{ item.CodigoCurso }} </label></td>
                        <td> <label> {{ item.NombreCurso }} </label></td>
                        <td> <label> {{ item.FechaInicio }} </label></td>
                        <td> <label> {{ item.FechaFin }} </label></td>
                        <td data-toggle="modal" data-target="#demoModal"
                        onclick="get_datos_curso('{{ item.id }}')" ><a href="#"><i class="ik ik-edit-2"></i></a></td>
                        <td onclick="delete_curso('{{ item.id }}')" ><a href="#"><i class="ik ik-trash-2"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block script %}

<script type="text/javascript"> 
    function add_curso(){

        var codigo_curso = $('#id_codigo_curso').val();
        var nombre_curso = $('#id_nombre_curso').val();
        var fecha_inicio = $('#id_fecha_inicio').val();
        var fecha_fin = $('#id_fecha_fin').val();
        var id_curso = $('#id_curso_edit').val();
        var request = $.ajax({
            type: "POST",
            url: "{% url 'add_curso_ajax' %}",
            data: {
                "id_curso": id_curso,
                "codigo_curso": codigo_curso,
                "nombre_curso": nombre_curso,
                "fecha_inicio": fecha_inicio,
                "fecha_fin": fecha_fin,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: response.campo,
                text: response.mensaje,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };
    function get_datos_curso(id_curso){
        var request = $.ajax({
            type: "POST",
            url: "{% url 'get_info_curso' %}",
            data: {
                "id_curso": id_curso,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $('#id_codigo_curso').val(response.data.CodigoCurso);
            $('#id_nombre_curso').val(response.data.NombreCurso);
            $('#id_fecha_inicio').val(moment(Date(response.data.FechaInicio)).format('YYYY-MM-DD'));
            $('#id_fecha_fin').val(moment(Date(response.data.FechaFin)).format('YYYY-MM-DD'));
            $('#id_curso_edit').val(response.data.id);
        });
    };
    function delete_curso(id_curso){
        var request = $.ajax({
            type: "POST",
            url: "{% url 'delete_curso_ajax' %}",
            data: {
                "id_curso": id_curso,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: response.campo,
                text: response.mensaje,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };
</script>
{% endblock %}

SchoolAdmin/templates/pages/consultar_estudiantes.html
{% extends 'bases/base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load crispy_forms_tags %}
{% load humanize %}
<div id="shadowdiv" class="card">
    <div class="card-header"><h3>Consultar Estudiantes</h3></div>
    <div class="card-body">
        <div class="text-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" 
                data-target="#demoModal">Agregar-Editar Estudiante</button>
        </div>
        <div class="modal fade" id="demoModal" tabindex="-1" role="dialog" aria-labelledby="demoModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="demoModalLabel">Agregar-Editar Estudiante</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <form class="forms-sample" method="POST">{% csrf_token %}
                            {% crispy filter_form %}
                            <input type="number" style="display:none" id="id_estudiante_edit">
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="add_estudiante()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="edit_create_direccion" tabindex="-1" role="dialog" aria-labelledby="edit_create_direccionLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="edit_create_direccionLabel">Agregar-Editar Direccion</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <form class="forms-sample" method="POST">{% csrf_token %}
                            {% crispy filter_form_direccion %}
                            <input type="number" style="display:none" id="direccion_id_edit">
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-primary" onclick="add_direccion()">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="DireccionModal" tabindex="-1" role="dialog" aria-labelledby="DireccionModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="DireccionModalLabel">Agregar-Editar Estudiante</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <table id="data_table_direccion" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Direccion</th>
                                    <th>Tipo Direccion</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-toggle="modal" data-target="#edit_create_direccion" data-dismiss="modal" class="btn btn-success">Nuevo +</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <table id="data_table" class="table table-striped">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha Nacimiento</th>
                    <th>Genero</th>
                    <th>Direcciones</th>
                    <th>Cursos</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr>
                        <td> <label> {{ item.Nombres }} </label></td>
                        <td> <label> {{ item.Apellidos }} </label></td>
                        <td> <label> {{ item.FechaNacimento }} </label></td>
                        <td> <label> {{ item.Genero }} </label></td>
                        <td data-toggle="modal" data-target="#DireccionModal"
                            onclick="get_direcciones('{{ item.id }}')"><a href="#" ><i class="ik ik-eye"></i></a></td>
                        <td><a href="{% url 'estudiante_curso' estudiante_id=item.id %}"><i class="ik ik-eye"></i></a></td>
                        <td><a data-toggle="modal" data-target="#demoModal"
                            onclick="get_datos_estudiante('{{ item.id }}')"><i class="ik ik-edit-2"></i></a></td>
                        <td onclick="delete_estudiante('{{ item.id }}')"><a href="#"><i class="ik ik-trash-2"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block script %}

<script type="text/javascript">
    var uri = "http://127.0.0.1:8000"
    function add_estudiante(){
        var nombres = $('#id_Nombres').val();
        var apellidos = $('#id_Apellidos').val();
        var fecha_nacimiento = $('#id_FechaNacimento').val();
        var genero = $('#id_Genero option:selected').val();
        var id_estudiante = $('#id_estudiante_edit').val();
        var request = $.ajax({
            type: "POST",
            url: uri + "/api_crear_editar_estudiantes/",
            headers: {
                'Authorization': 'Token  '+'{{ token }}',
            },
            data: {
                "id": id_estudiante,
                "nombres": nombres,
                "apellidos": apellidos,
                "fecha_nacimiento": fecha_nacimiento,
                "genero": genero,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: 'Mensaje',
                text: response.mensaje,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };
    function get_datos_estudiante(id_estudiante){
        var request = $.ajax({
            type: "POST",
            url: uri + "/api_datos_estudiantes/",
            headers: {
                'Authorization': 'Token  '+'{{ token }}',
            },
            data: {
                "id": id_estudiante,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $('#id_Nombres').val(response.data.Nombres);
            $('#id_Apellidos').val(response.data.Apellidos);
            $('#id_FechaNacimento').val(moment(Date(response.data.FechaNacimento)).format('YYYY-MM-DD'));
            $('#id_Genero').val(response.data.Genero);
            $('#id_estudiante_edit').val(response.data.id);
        });
    };
    function delete_estudiante(id_estudiante){
        var request = $.ajax({
            type: "POST",
            url: uri + "/api_eliminar_estudiantes/",
            headers: {
                'Authorization': 'Token  '+'{{ token }}',
            },
            data: {
                "id": id_estudiante,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: 'Mensaje',
                text: response.mensaje,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };

    function get_direcciones(id_estudiante){
        $('#id_estudiante_edit').val(id_estudiante);
        var request = $.ajax({
            type: "POST",
            url: "{% url 'get_direcciones' %}",
            data: {
                "estudiante_id": id_estudiante,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $("#data_table_direccion tr").remove();
            for (item in response.data){
                $('#data_table_direccion').append( '<tr><td>' + response.data[item].Direccion + '</td><td>' + response.data[item].TipoDireccionsrt + '</td><td data-toggle="modal" data-target="#edit_create_direccion" data-dismiss="modal" onclick="get_datos_direccion('+response.data[item].id+')" ><a href="#"><i class="ik ik-edit-2"></i></a></td><td onclick="delete_direccion('+response.data[item].id+')"><a href="#"><i class="ik ik-trash-2"></i></a></td></tr>' );
            }
        });
    };
    function add_direccion(){
        var direccion = $('#id_Direccion').val();
        var tipo_direccion = $('#id_TipoDireccion').val();
        var direccion_id_edit = $('#direccion_id_edit').val();
        var id_estudiante = $('#id_estudiante_edit').val();
        var request = $.ajax({
            type: "POST",
            url: "{% url 'create_edit_direccion' %}",
            data: {
                "direccion_id": direccion_id_edit,
                "direccion": direccion,
                "estudiante_id": id_estudiante,
                "tipo_direccion": tipo_direccion,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: 'Mensaje',
                text: response.data,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };
    function get_datos_direccion(direccion_id){
        var request = $.ajax({
            type: "POST",
            url: "{% url 'get_data_direccion' %}",
            data: {
                "direccion_id": direccion_id,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $('#id_Direccion').val(response.data[0].Direccion);
            $('#id_TipoDireccion').val(response.data[0].TipoDireccion);
            $('#direccion_id_edit').val(response.data[0].id);
            $('#id_estudiante_edit').val(response.data[0].Estudiante_id);
        });
    };
    function delete_direccion(direccion_id){
        var request = $.ajax({
            type: "POST",
            url: "{% url 'delete_direccion' %}",
            data: {
                "direccion_id": direccion_id,
                "csrfmiddlewaretoken":"{{ csrf_token }}",
            },
        });
        request.done(function(response) {
            $.toast({
                heading: 'Mensaje',
                text: response.mensaje,
                showHideTransition: 'slide',
                icon: 'info',
                loaderBg: '#46c35f',
                position: 'top-right'
            })
            setTimeout(function(){location.reload()}, 3000);
        });
    };

</script>
{% endblock %}